/**
 * Generated by Claude
 *
 * A persistent, data-agnostic DAG backed by two Kysely-managed tables.
 * Node *data* lives in your own tables; this only tracks ids and edges.
 *
 * Schema (created via createDAGTables):
 *
 *   <prefix>_nodes  (id TEXT PRIMARY KEY)
 *   <prefix>_edges  (from_id TEXT, to_id TEXT, PRIMARY KEY (from_id, to_id))
 *
 * Multiple independent DAGs are supported — just use different prefixes.
 *
 * Usage:
 *
 *   import { createDAG, createDAGTables } from "./kysely-dag.ts";
 *
 *   // One-time setup (idempotent):
 *   await createDAGTables(db, "tasks");
 *
 *   const dag = createDAG(db, "tasks");
 *
 *   await dag.addNode("a");
 *   await dag.addNode("b");
 *   await dag.addEdge("a", "b");          // a -> b  (b depends on a)
 *   await dag.topologicalSort();          // ["a", "b"]
 *   await dag.traverse((id, state) => {}); // depth-first, tree-expansion
 */

import type { Kysely, Transaction } from "kysely";
import { sql } from "kysely";

// ---------------------------------------------------------------------------
// Table shape — used as generic parameter for Kysely
// ---------------------------------------------------------------------------

type NodeRow = { id: string };
type EdgeRow = { from_id: string; to_id: string };

// ---------------------------------------------------------------------------
// TraversalState — mirrors the original interface
// ---------------------------------------------------------------------------

export interface TraversalState {
  /** The parent node id from which the current node was reached. Null for roots. */
  readonly parent: string | null;
  /** Depth of the current node (0 for roots). */
  readonly depth: number;
  /** Index of this node among its siblings. */
  readonly index: number;
  /** Total number of siblings. */
  readonly total: number;
}

export type DAGVisitor<C> = (id: string, state: TraversalState, context: C) => void;

// ---------------------------------------------------------------------------
// Public interface
// ---------------------------------------------------------------------------

export interface KyselyDAGraph {
  /** Add a node by id. No-op if it already exists. */
  addNode(id: string): Promise<void>;

  /** Returns true if a node with this id exists in the graph. */
  getNode(id: string): Promise<boolean>;

  /**
   * Add a directed edge from → to (meaning `to` depends on `from`).
   * Throws if the edge would create a cycle.
   * Both nodes are auto-created if they don't exist.
   */
  addEdge(from: string, to: string): Promise<void>;

  /**
   * Returns all node ids in topological order (depth-first, dependencies first).
   * Equivalent to: for every node, all its transitive dependencies appear before it.
   */
  topologicalSort(): Promise<string[]>;

  /** Returns the root node ids (nodes with no dependencies / in-edges to them as dependents). */
  roots(): Promise<string[]>;

  /** Returns all node ids in the graph. */
  nodes(): Promise<string[]>;

  /**
   * Traverses the graph depth-first from each root, calling visitor for every node.
   *
   * Behaves like a tree expansion: if a node is reachable via multiple paths it
   * will be visited multiple times — once per path, just like the original implementation.
   */
  traverse<C>(visitor: DAGVisitor<C>, context: C): Promise<void>;
}

// ---------------------------------------------------------------------------
// Schema creation
// ---------------------------------------------------------------------------

/**
 * Creates the two tables required for a DAG with the given prefix.
 * Safe to call multiple times (uses IF NOT EXISTS).
 *
 * @param db     A Kysely instance (any database type — tables are created via raw sql)
 * @param prefix Table name prefix, e.g. "tasks" → "tasks_nodes" + "tasks_edges"
 */
export async function createDAGTables(
  // deno-lint-ignore no-explicit-any
  db: Kysely<any>,
  prefix: string,
): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS ${sql.id(prefix + "_nodes")} (
      id TEXT NOT NULL,
      PRIMARY KEY (id)
    )
  `.execute(db);

  await sql`
    CREATE TABLE IF NOT EXISTS ${sql.id(prefix + "_edges")} (
      from_id TEXT NOT NULL,
      to_id   TEXT NOT NULL,
      PRIMARY KEY (from_id, to_id),
      FOREIGN KEY (from_id) REFERENCES ${sql.id(prefix + "_nodes")} (id),
      FOREIGN KEY (to_id)   REFERENCES ${sql.id(prefix + "_nodes")} (id)
    )
  `.execute(db);
}

/**
 * Drops the DAG tables for the given prefix.
 */
export async function dropDAGTables(
  // deno-lint-ignore no-explicit-any
  db: Kysely<any>,
  prefix: string,
): Promise<void> {
  await sql`DROP TABLE IF EXISTS ${sql.id(prefix + "_edges")}`.execute(db);
  await sql`DROP TABLE IF EXISTS ${sql.id(prefix + "_nodes")}`.execute(db);
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Creates a DAG backed by Kysely tables named `${prefix}_nodes` and `${prefix}_edges`.
 *
 * Call `createDAGTables(db, prefix)` once before using this.
 */
export function createDAG(
  // deno-lint-ignore no-explicit-any
  db: Kysely<any>,
  prefix: string,
): KyselyDAGraph {
  const nodesTable = prefix + "_nodes";
  const edgesTable = prefix + "_edges";

  // ------------------------------------------------------------------
  // Internal helpers
  // ------------------------------------------------------------------

  /** Load the full adjacency list: from_id -> [to_id, ...] */
  async function loadOutgoing(
    // deno-lint-ignore no-explicit-any
    trx: Kysely<any> | Transaction<any>,
  ): Promise<Map<string, string[]>> {
    const edges = await trx.selectFrom(edgesTable).selectAll().execute() as EdgeRow[];
    const out = new Map<string, string[]>();
    for (const { from_id, to_id } of edges) {
      let arr = out.get(from_id);
      if (!arr) { arr = []; out.set(from_id, arr); }
      arr.push(to_id);
    }
    return out;
  }

  /** Load set of all node ids */
  async function loadNodeIds(
    // deno-lint-ignore no-explicit-any
    trx: Kysely<any> | Transaction<any>,
  ): Promise<Set<string>> {
    const rows = await trx.selectFrom(nodesTable).select("id").execute() as NodeRow[];
    return new Set(rows.map((r) => r.id));
  }

  /**
   * Topological sort (Kahn's algorithm) over an in-memory adjacency list.
   * Returns null if a cycle is detected.
   */
  function topoSort(
    nodeIds: Set<string>,
    outgoing: Map<string, string[]>,
  ): string[] | null {
    // Build in-degree map
    const inDegree = new Map<string, number>();
    for (const id of nodeIds) inDegree.set(id, 0);
    for (const children of outgoing.values()) {
      for (const child of children) {
        inDegree.set(child, (inDegree.get(child) ?? 0) + 1);
      }
    }

    const queue: string[] = [];
    for (const [id, deg] of inDegree) {
      if (deg === 0) queue.push(id);
    }

    const sorted: string[] = [];
    while (queue.length > 0) {
      const id = queue.shift()!;
      sorted.push(id);
      for (const child of outgoing.get(id) ?? []) {
        const newDeg = (inDegree.get(child) ?? 1) - 1;
        inDegree.set(child, newDeg);
        if (newDeg === 0) queue.push(child);
      }
    }

    return sorted.length === nodeIds.size ? sorted : null; // null = cycle
  }

  /**
   * DFS topological sort — dependencies-first, matching the original behaviour.
   * Kahn gives breadth-first order; this gives depth-first order.
   */
  function dfsTopoSort(
    nodeIds: Set<string>,
    outgoing: Map<string, string[]>,
  ): string[] {
    const visited = new Set<string>();
    const result: string[] = [];

    function visit(id: string) {
      if (visited.has(id)) return;
      visited.add(id);
      for (const child of outgoing.get(id) ?? []) {
        visit(child);
      }
      result.push(id);
    }

    // Visit in insertion order (Map preserves it), roots first
    const roots = new Set(nodeIds);
    for (const children of outgoing.values()) {
      for (const c of children) roots.delete(c);
    }
    for (const root of roots) visit(root);
    // Also visit any remaining nodes not reachable from roots
    for (const id of nodeIds) visit(id);

    return result;
  }

  // ------------------------------------------------------------------
  // Implementation
  // ------------------------------------------------------------------

  async function addNode(id: string): Promise<void> {
    await db
      .insertInto(nodesTable)
      .values({ id } as NodeRow)
      .onConflict((oc) => oc.column("id").doNothing())
      .execute();
  }

  async function getNode(id: string): Promise<boolean> {
    const row = await db
      .selectFrom(nodesTable)
      .select("id")
      .where("id", "=", id)
      .executeTakeFirst();
    return row !== undefined;
  }

  async function addEdge(from: string, to: string): Promise<void> {
    await db.transaction().execute(async (trx) => {
      // Auto-create nodes
      await trx
        .insertInto(nodesTable)
        .values([{ id: from }, { id: to }] as NodeRow[])
        .onConflict((oc) => oc.column("id").doNothing())
        .execute();

      // Insert edge
      await trx
        .insertInto(edgesTable)
        .values({ from_id: from, to_id: to } as EdgeRow)
        .onConflict((oc) => oc.columns(["from_id", "to_id"]).doNothing())
        .execute();

      // Cycle check — load full graph and run Kahn's
      const nodeIds = await loadNodeIds(trx);
      const outgoing = await loadOutgoing(trx);
      const sorted = topoSort(nodeIds, outgoing);

      if (sorted === null) {
        throw new Error(
          `Adding edge [${from}] -> [${to}] would create a cycle`,
        );
      }
    });
  }

  async function topologicalSort(): Promise<string[]> {
    const [nodeIds, outgoing] = await Promise.all([
      loadNodeIds(db),
      loadOutgoing(db),
    ]);
    return dfsTopoSort(nodeIds, outgoing);
  }

  async function roots(): Promise<string[]> {
    // Roots are nodes that appear in no edge's to_id (nothing points to them)
    const allNodes = await db.selectFrom(nodesTable).select("id").execute() as NodeRow[];
    const nonRoots = await db
      .selectFrom(edgesTable)
      .select("to_id")
      .execute() as { to_id: string }[];

    const nonRootSet = new Set(nonRoots.map((r) => r.to_id));
    return allNodes.map((r) => r.id).filter((id) => !nonRootSet.has(id));
  }

  async function nodes(): Promise<string[]> {
    const rows = await db.selectFrom(nodesTable).select("id").execute() as NodeRow[];
    return rows.map((r) => r.id);
  }

  async function traverse<C>(visitor: DAGVisitor<C>, context: C): Promise<void> {
    const [outgoing, rootIds] = await Promise.all([
      loadOutgoing(db),
      roots(),
    ]);

    function visitNode(
      id: string,
      parent: string | null,
      depth: number,
      index: number,
      total: number,
    ): void {
      visitor(id, { parent, depth, index, total }, context);

      const children = outgoing.get(id) ?? [];
      children.forEach((childId, i) => {
        visitNode(childId, id, depth + 1, i, children.length);
      });
    }

    rootIds.forEach((rootId, i) => {
      visitNode(rootId, null, 0, i, rootIds.length);
    });
  }

  return { addNode, getNode, addEdge, topologicalSort, roots, nodes, traverse };
}