/**
 * Generated by Claude
 *
 * Kysely dialect for Deno SQLite
 *
 * Supports two SQLite backends:
 *   - `jsr:@db/sqlite`  (FFI-based, faster, recommended)
 *   - `node:sqlite`     (built-in, available in Deno >= 2.2)
 *
 * Usage - @db/sqlite backend (recommended):
 *
 *   import { Database } from "jsr:@db/sqlite";
 *   import { Kysely } from "npm:kysely";
 *   import { DenoSqliteDialect } from "./kysely-deno-sqlite.ts";
 *
 *   const db = new Kysely<MyDatabase>({
 *     dialect: new DenoSqliteDialect({ database: new Database("app.db") }),
 *   });
 *
 * Usage - node:sqlite backend:
 *
 *   import { DatabaseSync } from "node:sqlite";
 *   import { Kysely } from "npm:kysely";
 *   import { DenoSqliteDialect } from "./kysely-deno-sqlite.ts";
 *
 *   const db = new Kysely<MyDatabase>({
 *     dialect: new DenoSqliteDialect({ database: new DatabaseSync("app.db") }),
 *   });
 *
 * Permissions required for @db/sqlite (FFI):
 *   --allow-ffi --allow-env --allow-read --allow-write
 *
 * Permissions required for node:sqlite:
 *   --allow-read --allow-write
 */

import type {
  CompiledQuery,
  DatabaseConnection,
  DatabaseIntrospector,
  Dialect,
  DialectAdapter,
  Driver,
  Kysely,
  QueryResult,
} from "kysely";

import { SqliteAdapter, SqliteIntrospector, SqliteQueryCompiler } from "kysely";

// ---------------------------------------------------------------------------
// Database interface shims
// ---------------------------------------------------------------------------

/**
 * Matches `@db/sqlite`'s `Database`:
 *   - `prepare(sql).run(...params)` returns `number`  (rows changed)
 *   - `db.lastInsertRowId`          returns `number`
 */
export interface JsrSqliteDatabase {
  readonly lastInsertRowId: number;
  prepare(sql: string): {
    all(...params: unknown[]): Record<string, unknown>[];
    run(...params: unknown[]): number;
  };
  exec(sql: string): void;
  close(): void;
}

/**
 * Matches `node:sqlite`'s `DatabaseSync`:
 *   - `prepare(sql).run(...params)` returns `{ changes, lastInsertRowid }`
 */
export interface NodeSqliteDatabase {
  prepare(sql: string): {
    all(...params: unknown[]): Record<string, unknown>[];
    run(
      ...params: unknown[]
    ): { changes: number; lastInsertRowid: number | bigint };
  };
  exec(sql: string): void;
  close(): void;
}

export type SupportedDatabase = JsrSqliteDatabase | NodeSqliteDatabase;

/** Distinguishes @db/sqlite from node:sqlite at runtime. */
function isJsrDatabase(db: SupportedDatabase): db is JsrSqliteDatabase {
  return "lastInsertRowId" in db;
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface DenoSqliteDialectConfig {
  /**
   * An already-opened SQLite database instance.
   * Pass a `@db/sqlite` `Database` or `node:sqlite` `DatabaseSync`.
   */
  database: SupportedDatabase;

  /**
   * Optional callback invoked once after the connection is first created.
   * Useful for setting PRAGMAs (e.g. WAL mode, foreign keys).
   */
  onCreateConnection?: (connection: DatabaseConnection) => Promise<void>;
}

// ---------------------------------------------------------------------------
// Dialect
// ---------------------------------------------------------------------------

export class DenoSqliteDialect implements Dialect {
  readonly #config: DenoSqliteDialectConfig;

  constructor(config: DenoSqliteDialectConfig) {
    this.#config = config;
  }

  createAdapter(): DialectAdapter {
    return new SqliteAdapter();
  }

  createDriver(): Driver {
    return new DenoSqliteDriver(this.#config);
  }

  createIntrospector(db: Kysely<unknown>): DatabaseIntrospector {
    return new SqliteIntrospector(db);
  }

  createQueryCompiler() {
    return new SqliteQueryCompiler();
  }
}

// ---------------------------------------------------------------------------
// Driver
// ---------------------------------------------------------------------------

class DenoSqliteDriver implements Driver {
  readonly #config: DenoSqliteDialectConfig;
  #connection: DenoSqliteConnection | null = null;

  constructor(config: DenoSqliteDialectConfig) {
    this.#config = config;
  }

  async init(): Promise<void> {
    this.#connection = new DenoSqliteConnection(this.#config.database);
    if (this.#config.onCreateConnection) {
      await this.#config.onCreateConnection(this.#connection);
    }
  }

  async acquireConnection(): Promise<DatabaseConnection> {
    // SQLite is single-connection; return the same connection every time.
    return this.#connection!;
  }

  async beginTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(rawSql("BEGIN"));
  }

  async commitTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(rawSql("COMMIT"));
  }

  async rollbackTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(rawSql("ROLLBACK"));
  }

  async releaseConnection(_connection: DatabaseConnection): Promise<void> {
    // No-op: we reuse the single connection.
  }

  async destroy(): Promise<void> {
    this.#config.database.close();
  }
}

// ---------------------------------------------------------------------------
// Connection
// ---------------------------------------------------------------------------

class DenoSqliteConnection implements DatabaseConnection {
  readonly #db: SupportedDatabase;

  constructor(db: SupportedDatabase) {
    this.#db = db;
  }

  async executeQuery<R>(compiledQuery: CompiledQuery): Promise<QueryResult<R>> {
    const { sql, parameters } = compiledQuery;
    const params = parameters as unknown[];

    // Route SELECT-like statements through .all() to get rows back.
    if (/^\s*(select|pragma|with\b)/i.test(sql)) {
      const rows = this.#db.prepare(sql).all(...params) as R[];
      return { rows };
    }

    // Mutation — normalise the two different run() return shapes.
    if (isJsrDatabase(this.#db)) {
      // @db/sqlite: run() returns number of changed rows;
      // lastInsertRowId is a property on the database object.
      const changes = this.#db.prepare(sql).run(...params) as number;
      return {
        rows: [],
        numAffectedRows: BigInt(changes),
        insertId: BigInt(this.#db.lastInsertRowId),
      };
    } else {
      // node:sqlite: run() returns { changes, lastInsertRowid }
      const result = (this.#db as NodeSqliteDatabase)
        .prepare(sql)
        .run(...params) as {
          changes: number;
          lastInsertRowid: number | bigint;
        };
      return {
        rows: [],
        numAffectedRows: BigInt(result.changes),
        insertId: BigInt(result.lastInsertRowid),
      };
    }
  }

  // SQLite drivers are synchronous; we simulate streaming with chunked slices.
  async *streamQuery<R>(
    compiledQuery: CompiledQuery,
    chunkSize = 100,
  ): AsyncIterableIterator<QueryResult<R>> {
    const { sql, parameters } = compiledQuery;
    const params = parameters as unknown[];
    const allRows = this.#db.prepare(sql).all(...params) as R[];

    for (let i = 0; i < allRows.length; i += chunkSize) {
      yield { rows: allRows.slice(i, i + chunkSize) };
    }
  }
}

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/**
 * Build a minimal CompiledQuery for raw SQL statements (BEGIN, COMMIT, etc.).
 *
 * Kysely's CompiledQuery requires a `queryId`; we generate a throwaway UUID.
 * The `query` node is only used by plugins/logging so a stub is fine.
 */
function rawSql(sql: string): CompiledQuery {
  return {
    sql,
    parameters: [],
    queryId: { queryId: crypto.randomUUID() },
    query: { kind: "RawNode" } as unknown as CompiledQuery["query"],
  };
}

// ---------------------------------------------------------------------------
// Re-exports for convenience
// ---------------------------------------------------------------------------
export { Kysely, sql } from "kysely";
